version: '2.3'
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile-deploy
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - /static:/code/app/static
    runtime: nvidia
