version: '3.7'
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:8000
    volumes:
      - ./app/endpoints:/code/app/endpoints
      - ./app/models:/code/app/models
      - ./app/schemas:/code/app/schemas
      - /static:/code/app/static
      - ./app:/code/app