version: '3.7'
services:
  db:
    image: mysql
    volumes:
      - /var/local/mysql:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./scripts:/home/scripts
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    restart: always
    env_file: .env